### ISSUE TITLE
how to generate the graph png

### ISSUE THREAD

**Issue by bluehumor** [daniakalomiris/university-chatbot#1]
what tool you use to generate the rdf_graph.png

**Comment by daniakalomiris** [comment]
@bluehumor I took the content of the  `turtle.ttl` file and pasted it [here](http://www.ldf.fi/service/rdf-grapher) which generated the PNG file of the graph.

**Comment by bluehumor** [comment]
Thanks for your answer. It is a wonderful effect, but do you know how to let it support chinese character?

**Comment by daniakalomiris** [comment]
@bluehumor Unfortunately, I do not and the RDF Grapher does not provide which languages are supported. You can try to use Chinese characters and see if they appear in your graph.

**Comment by bluehumor** [comment]
Thank you very much.
