### ISSUE TITLE
raw_input undefine in chatbot.py

### ISSUE THREAD

**Issue by HQ1791** [daniakalomiris/university-chatbot#2]
Hello, 
I am trying to execute the code and I am getting the following error. Could you tell me how to get rid of this error? Thanks!
`$ python chatbot.py
----------------------------------------------------------------------------------------------------
Welcome to the University Chatbot! Please enter your questions and enter "quit" when you are done.
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\university-chatbot-master\chatbot.py", line 186, in <module>
    command_interface()
  File "C:\Users\admin\Desktop\university-chatbot-master\chatbot.py", line 177, in command_interface
    s = raw_input('> ')
        ^^^^^^^^^
NameError: name 'raw_input' is not defined`

**Comment by daniakalomiris** [comment]
it looks like `raw_input()` was renamed to `input()` in [Python 3](https://docs.python.org/3/whatsnew/3.0.html#builtins). I can't remember why I had done the reverse in an older [commit](https://github.com/daniakalomiris/university-chatbot/commit/b0c2ec52f253c1e3171b4404bc6c91716bd22cfd) but I've changed the naming which fixes the error!

**Comment by HQ1791** [comment]
Thankyou! its working now.
